<a href="https://colab.research.google.com/github/JJ-HMFIC/ML_Basic/blob/main/ML_Basic_Ch12_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ch 12

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
# x_data = [[0, 1, 0, 2, 3, 3]]  # hihell
y_data = [[1, 0, 2, 3, 3, 4]]  # ihello

In [ ]:
num_classes = 5
input_dim = 5  # one-hot size, same as hidden_size to directly predict one-hot
sequence_length = 6  # |ihello| == 6
learning_rate = 0.001

In [ ]:
x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)

In [ ]:
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [ ]:
model = tf.keras.Sequential()

In [ ]:
# make cell and add it to RNN layer
# input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim

cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(sequence_length, input_dim))
# LSTMCell은 LSTM(Long Short-Term Memory) 네트워크의 하나의 셀을 정의
# units 매개변수는 LSTM 셀의 출력 크기
# input_shape는 입력 데이터의 형태를 정의
# sequence_length는 시퀀스의 길이, input_dim은 입력 벡터의 차원

model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))
# RNN 레이어는 주어진 셀(cell)을 사용하여 RNN을 구성
# return_sequences=True로 설정되어 있으므로, 이 RNN 레이어는 출력 시퀀스를 반환
# 만약 return_sequences를 False로 설정하면, 마지막 시간 단계의 출력만 반환

In [ ]:
# single LSTM layer can be used as well instead of creating LSTMCell
# tf.model.add(tf.keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, input_dim), return_sequences=True))

# fully connected layer
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))
# TimeDistributed 레이어는 내부에 있는 레이어를 시간 분배(distribute)하여 각 시간 단계에서 같은 가중치를 사용하는 레이어
# Dense 레이어는 완전 연결 층을 의미
# num_classes는 출력의 개수
# 출력을 확률 분포로 변환하기 위해 소프트맥스 활성화 함수를 사용

model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
                 metrics=['accuracy'])
# metrics는 모델의 성능을 측정할 지표로, 여기서는 정확도('accuracy')를 사용

In [ ]:
# train

model.fit(x_one_hot, y_one_hot, epochs=50)
model.summary()

Epoch 1/50
1/1 [==============================] - 0s 28ms/step - loss: 1.4647 - accuracy: 0.3333
Epoch 2/50
1/1 [==============================] - 0s 28ms/step - loss: 1.4634 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 24ms/step - loss: 1.4622 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 26ms/step - loss: 1.4609 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 40ms/step - loss: 1.4597 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 31ms/step - loss: 1.4584 - accuracy: 0.3333
Epoch 7/50
1/1 [==============================] - 0s 30ms/step - loss: 1.4571 - accuracy: 0.3333
Epoch 8/50
1/1 [==============================] - 0s 30ms/step - loss: 1.4559 - accuracy: 0.3333
Epoch 9/50
1/1 [==============================] - 0s 31ms/step - loss: 1.4546 - accuracy: 0.3333
Epoch 10/50
1/1 [==============================] - 0s 21ms/step - loss: 1.4533 - accuracy: 0.3333
Epoch 11/50
1/1 [============

In [ ]:
predictions = model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))



1/1 [==============================] - 0s 18ms/step
[[0.20831332 0.20931685 0.18990122 0.27444676 0.11802179]
 [0.20996173 0.21346848 0.19188713 0.27454385 0.11013877]
 [0.21071006 0.21762232 0.19450228 0.27486882 0.10229656]
 [0.18909988 0.19129631 0.16272466 0.30719653 0.14968257]
 [0.18087387 0.15218899 0.13989438 0.29181442 0.23522836]
 [0.1781055  0.13063982 0.12936418 0.2673108  0.29457968]]
	Prediction str:  lllllo
