<a href="https://colab.research.google.com/github/JJ-HMFIC/ML_Basic/blob/main/ML_Basic_Ch07_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ch 07

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
# train data
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# test data
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [ ]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [ ]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y* tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [ ]:
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [ ]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val,_ = sess.run([cost,W,optimizer],
                                  feed_dict={X: x_data, Y: y_data}) # 학습
    print(step, cost_val,W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 4.4438286 [[-0.05216063 -0.27056918 -0.96913135]
 [ 0.04904243  1.3158007   1.2331878 ]
 [ 0.5936087  -0.47604668  0.08144301]]
Prediction: [0 0 0]
Accuracy:  0.0
1 1.9457314 [[-0.05715142 -0.25645527 -0.97825444]
 [ 0.12269559  1.3970658   1.0782695 ]
 [ 0.63338405 -0.3657768  -0.06860225]]
Prediction: [0 0 0]
Accuracy:  0.0
2 1.73267 [[-0.07045465 -0.27017358 -0.9512329 ]
 [ 0.15388033  1.3164632   1.1276873 ]
 [ 0.6284836  -0.40153554 -0.02794305]]
Prediction: [0 0 0]
Accuracy:  0.0
3 1.6622884 [[-0.08943771 -0.26805517 -0.93436825]
 [ 0.15610091  1.3235118   1.1184181 ]
 [ 0.5960644  -0.35650408 -0.04055534]]
Prediction: [0 0 0]
Accuracy:  0.0
4 1.6306751 [[-0.10349889 -0.27299765 -0.91536456]
 [ 0.1825936   1.2922959   1.1231413 ]
 [ 0.5879084  -0.34776047 -0.04114294]]
Prediction: [0 0 0]
Accuracy:  0.0
5 1.6042118 [[-0.11933821 -0.27437663 -0.8981463 ]
 [ 0.19974273  1.2805012   1.1177869 ]
 [ 0.5710524  -0.3214957  -0.05055165]]
Prediction: [0 0 0]
Accuracy:  0.0
6 1.5790751 

In [ ]:
# big alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1.5).minimize(cost)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val,_ = sess.run([cost,W,optimizer],
                                  feed_dict={X: x_data, Y: y_data}) # 학습
    print(step, cost_val,W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 4.8600016 [[ 0.19709376 -0.20132339  0.3915378 ]
 [ 2.7793863  -1.7013351   0.52434605]
 [ 1.267504   -3.4358654   1.0058554 ]]
Prediction: [0 0 0]
Accuracy:  0.0
1 19.118248 [[-0.9216347   0.3611765   0.9477664 ]
 [-1.3325112   0.9236649   2.011244  ]
 [-2.8442442  -0.62336564  2.3051043 ]]
Prediction: [2 2 2]
Accuracy:  1.0
2 22.997473 [[-0.5466347   0.92350423  0.0104388 ]
 [ 1.1049888   3.5483174  -3.0509079 ]
 [-0.40674424  2.1889591  -2.9447198 ]]
Prediction: [1 1 1]
Accuracy:  0.0
3 20.394226 [[-0.17164105 -0.01398933  0.5729388 ]
 [ 3.542476   -0.38916898 -1.5509079 ]
 [ 2.0307493  -1.5610337  -1.6322198 ]]
Prediction: [0 0 0]
Accuracy:  0.0
4 21.05377 [[-1.296637    0.5485082   1.1354374 ]
 [-0.5825155   2.235826   -0.05091059]
 [-2.094246    1.2514639  -0.31972122]]
Prediction: [1 1 1]
Accuracy:  0.0
5 13.85705 [[-0.9216377  -0.38625878  1.6952051 ]
 [ 1.8549836  -1.6961479   1.4435652 ]
 [ 0.3432536  -2.495718    0.98996186]]
Prediction: [2 2 2]
Accuracy:  1.0
6 15.710712 

In [ ]:
# small alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-10).minimize(cost)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val,_ = sess.run([cost,W,optimizer],
                                  feed_dict={X: x_data, Y: y_data}) # 학습
    print(step, cost_val,W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
1 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
2 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
3 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
4 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
5 7.052713 [[ 0.07418169 -1.5911446   2.379905  ]
 [ 0.25526816 -1.0191307   1.6372876 ]
 [ 0.4585796  -1.2151014  -1.2678862 ]]
Prediction: [2 2 2]
Accuracy:  1.0
6 7.052713 [[ 0.

In [ ]:
import numpy as np

In [ ]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
# Non normalized imputs, Nan

In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
   cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
   print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
1501 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1502 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1503 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1504 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1505 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1506 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1507 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1508 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1509 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1510 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1511 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1512 Co

In [ ]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [ ]:
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  0.25199008 
Prediction:
 [[1.0247236 ]
 [1.6278822 ]
 [1.1584369 ]
 [0.59471095]
 [0.9295889 ]
 [0.9572283 ]
 [0.55747294]
 [0.71500653]]
1 Cost:  0.25197622 
Prediction:
 [[1.024704  ]
 [1.6278611 ]
 [1.1584195 ]
 [0.59469754]
 [0.92957306]
 [0.95721304]
 [0.5574619 ]
 [0.71499497]]
2 Cost:  0.25196236 
Prediction:
 [[1.0246844 ]
 [1.62784   ]
 [1.158402  ]
 [0.5946842 ]
 [0.92955726]
 [0.9571976 ]
 [0.5574509 ]
 [0.71498346]]
3 Cost:  0.25194854 
Prediction:
 [[1.0246646]
 [1.627819 ]
 [1.1583846]
 [0.5946708]
 [0.9295415]
 [0.9571822]
 [0.5574398]
 [0.7149719]]
4 Cost:  0.25193462 
Prediction:
 [[1.024645  ]
 [1.6277977 ]
 [1.1583669 ]
 [0.59465736]
 [0.92952573]
 [0.9571669 ]
 [0.5574287 ]
 [0.7149603 ]]
5 Cost:  0.25192076 
Prediction:
 [[1.0246253 ]
 [1.6277765 ]
 [1.1583495 ]
 [0.594644  ]
 [0.92950994]
 [0.95715153]
 [0.55741775]
 [0.7149487 ]]
6 Cost:  0.25190687 
Prediction:
 [[1.0246055 ]
 [1.6277553 ]
 [1.158332  ]
 [0.5946306 ]
 [0.92949414]
 [0.95713615]
 [0.5574