<a href="https://colab.research.google.com/github/JJ-HMFIC/ML_Basic/blob/main/ML_Basic_Ch06_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ch 06

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5],
                                                        [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]] # one-hot Encoding

X = tf.placeholder("float", [None,4])
Y = tf.placeholder("float", [None,3])
nb_classes = 3 # y의 개수와 동일

In [ ]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') # 4= 들어오는 값 = X, nb_classes= 나가는 값
b = tf.Variable(tf.random_normal([nb_classes]), name='bias') # 출력값과 같음

In [ ]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [ ]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  sess.run(optimizer, feed_dict={X:x_data, Y: y_data})
  if step %200 ==0:
    print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))


0 12.104818
200 0.6349002
400 0.51543766
600 0.43353316
800 0.3618114
1000 0.29058594
1200 0.2357335
1400 0.21382105
1600 0.19550085
1800 0.17995432
2000 0.166607


In [ ]:
a= sess.run(hypothesis, feed_dict={X: [[1,11,7,9]]})
print(a, sess.run(tf.arg_max(a,1)))
# [0.00001 0.9 0.0001]// 1= 012 중 1 선택

Instructions for updating:
Use `tf.math.argmax` instead


[[1.3412020e-02 9.8657739e-01 1.0628607e-05]] [1]


In [ ]:
all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                          [1, 3, 4, 3],
                                          [1, 1, 0, 1]]})
print(all, sess.run(tf.arg_max(all, 1)))
#argmax = argument중 가장 큰 인덱스 리턴

[[1.34119885e-02 9.86577392e-01 1.06286070e-05]
 [7.88753331e-01 1.92924172e-01 1.83224566e-02]
 [2.57732609e-08 4.34573740e-04 9.99565423e-01]] [1 0 2]
