<a href="https://colab.research.google.com/github/JJ-HMFIC/ML_Basic/blob/main/ML_Basic_Ch08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ch 08

In [ ]:
import numpy as np
import pprint

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

1차원 배열

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape (7,)= 1차원을 의미함

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)


In [ ]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


2차원 배열

In [ ]:
# 2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


shape, rank, axis

In [ ]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() #

array([4], dtype=int32)

In [ ]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval() # 대괄호가 몇개 있냐 = 랭크 = 2
# 한 괄호에 2개의 원소 (두 번째 2)
# 대괄호 세트가 몇개 있느냐 (첫 번째 2)

array([2, 2], dtype=int32)

In [ ]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()
# 랭크 = 4
# [] 하나당 원소의 개수 4개 = 4
# 큰 [] 당 []의 개수 3개 = 3
# 전체 []의 개수 = 2 개
# 제일 바깥쪽 [] = 1개

array([1, 2, 3, 4], dtype=int32)

In [ ]:
[ #axis = 0
    [  # axis = 1
        [ # axis= 2
            [1,2,3,4], # axis = 3
            [5,6,7,8],
            [9,10,11,12]
        ],
        [                                                    #axis = -1
            [13,14,15,16],
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

matmul vs mulitply

In [ ]:
matrix1 = tf.constant([[1.,2.,],[ 3.,4.]]) # (2,2)
matrix2 = tf.constant([[1.],[2.]]) # (2,1)
print("Matrix 1 shape:", matrix1.shape )
print("Matrix 2 shape:", matrix2.shape )

tf.matmul(matrix1, matrix2).eval() # 행렬곱

Matrix 1 shape: (2, 2)
Matrix 2 shape: (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [ ]:
(matrix1*matrix2).eval()

array([[1., 2.],
       [6., 8.]], dtype=float32)

broadcasting

In [ ]:
matrix1 = tf.constant([[3., 3.]]) #(1,2)
matrix2 = tf.constant([[2.],[2.]])#(2,1)
(matrix1+matrix2).eval() #

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval() # 같은 shape이라서 일대일 매핑

array([[5., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval() # shape이 달라 3,3으로 자동 매핑 = broadcasting

array([[4., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.]) # rank가 달라도 계산 가능
(matrix1+matrix2).eval()

array([[4., 6.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1+matrix2).eval() # 다른 형태의 tensor도 가능

array([[4., 5.],
       [5., 6.]], dtype=float32)

Reduce Mean/Sum


In [ ]:
tf.reduce_mean([1, 2], axis=0).eval()
# 1.5가 나오지 않음 , 원소가 정수라서

1

In [ ]:
x = [[1., 2.], #-> axis =1
     [3., 4.]]
# ↓ axis = 0

tf.reduce_mean(x).eval()

2.5

In [ ]:
tf.reduce_mean(x, axis=0).eval()
# axis = 0 , 세로축을 중심으로

array([2., 3.], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=1).eval()
# # axis = 1 , 가로축을 중심으로

array([1.5, 3.5], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=-1).eval()
# -1 : 가장 안쪽에 있는 값으로 평균내어라

array([1.5, 3.5], dtype=float32)

In [ ]:
tf.reduce_sum(x).eval()

10.0

In [ ]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [ ]:
tf.reduce_sum(x, axis=-1).eval()


array([3., 7.], dtype=float32)

In [ ]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

Argmax

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [ ]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [ ]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

Reshape

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
t.shape
# 가장 작은 []에서 원소의 개수 = 3
# 두번째로 작은 []의 세트의 개수 = 2
# 가장 큰 [] 묶음 = 2

(2, 2, 3)

In [ ]:
tf.reshape(t, shape=[-1, 3]).eval() # 원소의 개수 3개로 알아서 reshape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).eval()
# 제일 안쪽 차원의 원소의 개수 = 3
# 그 다음 차원의 원소의 개수 = 1
# => 아래와 같이 2차원 배열 형성 [[ㅁ,ㅁ,ㅁ]]

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [ ]:
tf.reshape(t, shape=[-1, 2, 3]).eval()
# 제일 안쪽 차원의 원소의 개수 = 3
# 그 다음 차원의 원소의 개수 = 1
# => [ㅁ,ㅁ,ㅁ]가 두 세트 있음

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Reshape (squeeze, expand)

In [ ]:
tf.squeeze([[0], [1], [2]]).eval()
# 쫙 펴준다.

array([0, 1, 2], dtype=int32)

In [ ]:
tf.expand_dims([0, 1, 2], 1).eval()
# 텐서의 shape 변환 , 차원 더하기

array([[0],
       [1],
       [2]], dtype=int32)

One-hot

In [ ]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
# 0 = [1., 0., 0.]
# 1 = [0., 1., 0.]
# 2 = [0., 0., 1.] 로 변환 , depth 가 3 이라 []안에 세 원소 존재

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [ ]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

Casting

In [ ]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

Stack

In [ ]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

Ones like and Zeros like

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()
# 같은 모양을 1로 채워줌

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
